### PR TITLE
refactor: improve error feedback for missing parenthesis in alg

### LINKED ISSUE #256: Error notice in calc that seems correct
CalcPvr:       ExportChokeModel
         Text1=  "Choke process setpoint from CA block"
         Text2=  "Deadband i prosess 0.5 bar, modellgain ca 1/3 choke/innløpstrykk."
           Alg=  "setmeas(EXPZPC_Y, if(and (EXPZPC_XAPC>0.5, abs(EXPZPC_YX-EXPZPC_XOUT)>0.5), min(max(filt(EXPZPC_Y+3*InletPressure_Deviation+0.01*PIC_Integral,0.1),0),100),EXPZPC_Y))"

image

Missing closing paranthesis at end of grouping.septic(E201)

### PR DESCRIPTION
**Pull request by vetlek**
Closes #256

### CODE REVIEW

**Review by einarsi — COMMENTED** [review]
Somewhat inconsistent error messages. Example:
image

1. Space between abs and (
image
2. Wrap abs in parenthesis
image
3. Space between if and (
image

**Comment by vetlek** [comment]
> Somewhat inconsistent error messages. Example: image
> 
> 1. Space between abs and (
>    image
> 2. Wrap abs in parenthesis
>    image
> 3. Space between if and (
>    image

The worrying case is 1. Should report that that only one value can be provided as an argument to a function.

**Comment by einarsi** [comment]
> > Somewhat inconsistent error messages. Example: image
> > 
> > 1. Space between abs and (
> >    image
> > 2. Wrap abs in parenthesis
> >    image
> > 3. Space between if and (
> >    image
> 
> The worrying case is 1. Should report that that only one value can be provided as an argument to a function.

Is it expected that the warnings for the three cases should be the same as reported above also after the last commit?

**Comment by vetlek** [comment]
The first case should be different, reporting an error instead of warning

**Review by einarsi — APPROVED** [review]

**Pull request merged**
