### PR TITLE
fix: update parsing and highlighting of invalid comments

### PR DESCRIPTION
**Pull request by vetlek**
Closing #362

### CODE REVIEW

**Review by einarsi — COMMENTED** [review]
Can verify that comments w/o the required space are not treated as comments in this branch. But it does look sort of weird:

image
Note that not only is the error message on the invalid comment context-sensitive, but it also adds diagnostics on another line. 
image
Can this be handled cleaner? For instance trigger a diagnosis when // is not followed by whitespace and report that the comment syntax is wrong, and have that diagnosis as higher priority than attribute diagnosis?

**Comment by einarsi** [comment]
Also, when adding this kind of erroneous comment at the end of a template file, there may be issues (corner-case, I know, but for completeness' sake...):
image

**Comment by vetlek** [comment]
> Also, when adding this kind of erroneous comment at the end of a template file, there may be issues (corner-case, I know, but for completeness' sake...): image

I know. It should be visual indication in the template file that the comment is incomplete (not rendered as comment). Can't see that we can do more.

**Comment by vetlek** [comment]
> Can verify that comments w/o the required space are not treated as comments in this branch. But it does look sort of weird:
> 
> image Note that not only is the error message on the invalid comment context-sensitive, but it also adds diagnostics on another line. image Can this be handled cleaner? For instance trigger a diagnosis when // is not followed by whitespace and report that the comment syntax is wrong, and have that diagnosis as higher priority than attribute diagnosis?

It adds the error message on another line since the erroneous comment is interpreted as a value for the alg attribute, but have the wrong data type for alg (think it is parsed as a path). I think that "random" error messages poping up when you use an erroneous comment helps to indicate that there is something wrong and it should be obvious for the user what is causing the issue. Having priorities on diagnostics is unnecessary complicated.

**Comment by einarsi** [comment]
> I know. It should be visual indication in the template file that the comment is incomplete (not rendered as comment). Can't see that we can do more.

Finishing the template file like this has no indication that the comment is not complete:
image

Shouldn't the syntax highlighting pick and diagnostics pick up on the missing space before '*/'? I don't understand how the above is different from these two cases:
image

image

**Review by einarsi — APPROVED** [review]

**Pull request merged**
